name: relation
description: the stream representation of the relations of the entities and widget utilities
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #rx
  rxdart: 0.24.1

  mwwm:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-RIG-21
      path: mwwm

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.7.0

flutter:
