name: storage
version: "0.0.1-dev.0"
description: Data storage wrap
repository: https://github.com/surfstudio/SurfGear/tree/dev/packages/storage

dependencies:
  flutter:
    sdk: flutter
  localstorage: 3.0.1+4
  surf_lint_rules:
    git:
      url: "https://gitlab.com/surfstudio/public/flutter-standard.git"
      path: packages/surf_lint_rules

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version: 1
  is_plugin: false
  path: storage
  separate_repo_url:
  hostUrl:
