name: surf_network
version: "0.0.1-dev.5"
description: Network implementation for Flutter
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/surf_network"

dependencies:
  flutter:
    sdk: flutter
  surf_logger: 0.0.1-dev.5
  dio: ^3.0.8
  http: ^0.12.0+4
  http_parser: ^3.1.3
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: surf_network
  separate_repo_url:
  hostUrl:
