name: push_demo
description: A new Flutter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_core: ^1.0.4
  firebase_messaging: ^9.1.2
  flutter:
    sdk: flutter
  logger: ^1.0.0
  push_notification:
    path: ../

dev_dependencies:
  surf_lint_rules: ^1.0.0

flutter:
  uses-material-design: true
