name: bottom_sheet
description: Custom bottom sheet widget.
version: 0.0.1
author:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: