# Customizing static analysis
# https://dart.dev/guides/language/analysis-options/
# https://dart-lang.github.io/linter/lints/

#include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  exclude:
    # Web
    - 'web/**'
    # Build
    - 'build/**'
    # Generated code
    - 'lib/**.g.dart'
    - 'lib/**.freezed.dart'
    - 'lib/**.graphql.dart'
    - 'lib/generated_plugin_registrant.dart'
    - '.test_coverage.dart'
    # Assets
    - 'assets/**'
    # Mocks for test
    - 'test/data/**'

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Info
    todo: info
    directives_ordering: info
    always_declare_return_types: info

    # Warning
    unsafe_html: warning
    prefer_relative_imports: warning
    no_logic_in_create_state: warning
    empty_catches: warning

    # Error
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    close_sinks: error
    valid_regexps: error
    always_require_non_null_named_parameters: error

linter:
  rules:
    # Disabled
    always_specify_types: false
    avoid_as: false
    avoid_redundant_argument_values: false
    comment_references: false # Unused because https://github.com/dart-lang/sdk/issues/36974
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    prefer_double_quotes: false
    public_member_api_docs: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    use_key_in_widget_constructors: false
    avoid_web_libraries_in_flutter: false
    always_put_control_body_on_new_line: false
    #diagnostic_describe_all_properties: false # ???

    # Enabled
    # always_put_required_named_parameters_first: true
    # avoid_print: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    avoid_slow_async_io: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    cancel_subscriptions: true
    cascade_invocations: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_logic_in_create_state: true
    no_runtimeType_toString: true
    only_throw_errors: true
    overridden_fields: true
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    # sort_pub_dependencies: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_null_aware_assignments: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true
    use_raw_strings: true
    use_string_buffers: true
    valid_regexps: true
    void_checks: true

    # Pedantic 1.9.0
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    camel_case_extensions: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_closures: true
    omit_local_variable_types: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true

    # Effective_dart 1.2.0
    camel_case_types: true
    file_names: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    directives_ordering: true
    package_api_docs: true
    implementation_imports: true
    prefer_relative_imports: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_brace_in_string_interps: true
    avoid_function_literals_in_foreach_calls: true
    prefer_function_declarations_over_variables: true
    unnecessary_lambdas: true
    unnecessary_getters_setters: true
    prefer_initializing_formals: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    use_to_and_as_if_applicable: true
    one_member_abstracts: true
    avoid_classes_with_only_static_members: true
    prefer_mixin: true
    use_setters_to_change_properties: true
    avoid_setters_without_getters: true
    avoid_returning_null: true
    avoid_returning_this: true
    type_annotate_public_apis: true
    avoid_types_on_closure_parameters: true
    avoid_private_typedef_functions: true
    avoid_positional_boolean_parameters: true
    hash_and_equals: true
    avoid_equals_and_hash_code_on_mutable_classes: true