name: simple_messenger
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.2.2
  cupertino_icons: ^1.0.0
  firebase_core: ^1.3.0
  flutter:
    sdk: flutter
  mwwm: ^2.0.0
  provider: ^5.0.0
  relation: ^3.1.0-dev.1
  surf_lint_rules: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
