name: permission_handler_example
description: Demonstrates how to use the permission_handler plugin.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  permission_handler:
    path: ../

flutter:
  uses-material-design: true