#!/usr/bin/env bash

build_type=release

### FUNCTIONS

function clean() {
    ./clean_ios.sh
}

### END FUNC

echo "Parameters" $1 $2
while [[ -n "$1" ]]; do # while loop starts

        case "$1" in

            -qa )           build_type=qa
                            ;;

            -release )      build_type=release
                            ;;

            -h )            dart ./script/ios/build_impl/usage.dart
                            exit
                            ;;

            *)              dart ./script/ios/build_impl/usage.dart
                            exit
                            ;;

            esac

         shift

done

### MAIN

dart ./script/android/build_impl/build.dart ${build_type}
clean
