name: scenario
description: scenario library.
version: 0.0.1
author:
homepage:
repository:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: scenario
  separate_repo_url:
  hostUrl:
