name: surfpay
description: Plugin for making payments on android and ios
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 0.19.0

  surf_lint_rules:
    path: ../surf_lint_rules

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.surf.surfpay
        pluginClass: SurfpayPlugin
      ios:
        pluginClass: SurfpayPlugin

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: true
  path: surf_pay
  separate_repo_url:
  hostUrl: