# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.108.0"

prod_bundle_id = "YOUR_ID" ## your id here todo
dev_bundle_id = "YOUR_ID" ## your id here todo

prod_target = "Runner"
prod_scheme = "Runner"

default_platform :ios

platform :ios do
  lane :build do |options|
    xcodebuild(
      workspace: "Runner.xcworkspace",
      scheme: prod_scheme,
      configuration: "Debug",
      clean: options[:clean],
      build: true,
      destination: "generic/platform=iOS\" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=\""
    )
  end

   desc "Submit a new Beta Build to Firebase"
  lane :beta do

    cocoapods(use_bundle_exec:true)

    sigh(
      development: true,
      app_identifier: dev_bundle_id
    )

    gym(
      scheme: "Runner",
      configuration: "Release",
      clean: true,
      include_bitcode: false,
      export_options: { compileBitcode: false},
      export_method: "development",
      export_xcargs: "-allowProvisioningUpdates"
    )

    #upload_to_fad(app_id: "1:408916197886:ios:9789acc2112ee7e57240af") #todo your id

    sh("rm ../*.mobileprovision")
  end

  # Need check
  desc "Submit a new Release Build to Firebase"
  lane :release do
    #cocoapods(use_bundle_exec: false)

    cert(development: false)

    sigh(
      development: false,
      app_identifier: prod_bundle_id
    )

    gym(
      scheme: prod_scheme,
      configuration: "Release",
      clean: true,
      include_bitcode: false,
      export_options: { compileBitcode: false},
      export_method: "app-store"
    )

    #upload_to_fad(app_id: "1:353274792412:ios:c4c0307b647a34873b6719") #todo your id

    sh("rm ../*.mobileprovision")
  end

  lane :upload_to_fad do |options|
    app_id = options[:app_id]
    firebase_app_distribution(
        app: "#{app_id}",
        groups: "surf", #todo your group name
        release_notes: "QA",
        firebase_cli_path: "/usr/local/bin/firebase",
        firebase_cli_token: "$FIREBASE_TOKEN",
    )
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics