// Mocks generated by Mockito 5.0.13 from annotations
// in mwwm_example/test/features/auth/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mwwm_example/features/auth/data/datasources/auth_local_data_source.dart'
    as _i3;
import 'package:mwwm_example/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i5;
import 'package:mwwm_example/features/auth/data/models/auth_data_model.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAuthDataModel extends _i1.Fake implements _i2.AuthDataModel {}

/// A class which mocks [AuthLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSourceImpl extends _i1.Mock
    implements _i3.AuthLocalDataSourceImpl {
  MockAuthLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthDataModel> loadAuthData() => (super.noSuchMethod(
          Invocation.method(#loadAuthData, []),
          returnValue: Future<_i2.AuthDataModel>.value(_FakeAuthDataModel()))
      as _i4.Future<_i2.AuthDataModel>);
  @override
  _i4.Future<void> saveAuthData(_i2.AuthDataModel? authDataModel) =>
      (super.noSuchMethod(Invocation.method(#saveAuthData, [authDataModel]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [AuthRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSourceImpl extends _i1.Mock
    implements _i5.AuthRemoteDataSourceImpl {
  MockAuthRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthDataModel> authenticate(
          {String? login, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #authenticate, [], {#login: login, #password: password}),
              returnValue:
                  Future<_i2.AuthDataModel>.value(_FakeAuthDataModel()))
          as _i4.Future<_i2.AuthDataModel>);
  @override
  String toString() => super.toString();
}
