name: example
description: Example of using mixed list.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # static analysis
  pedantic: ^1.7.0

  # http
  http: ^0.12.0

  #surfstudio
  mixed_list:
    path: ..

  # datalist
  datalist:
    git:
      url: https://gitlab.com/builder-surf/flutter-standard.git
      ref: project-RIG-12
      path: datalist

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - res/assets/images/