name: virtual_keyboard
version: "1.0.0"
description: Keyboard widget for use in widget tree
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/virtual_keyboard"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"
publish_to: none

dependencies:
  flutter:
    sdk: flutter

  ink_widget: ^2.0.0

dev_dependencies:
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: virtual_keyboard
  hostUrl:
  separate_repo_url:
