name: virtual_keyboard
description: Keyboard widget for use in widget tree
version: 0.0.1-dev.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ink_widget:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-LLC
      path: packages/ink_widget

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: ink_widget
  hostUrl: