name: virtual_keyboard
version: "0.0.1-dev.0"
description: Keyboard widget for use in widget tree
repository: https://github.com/surfstudio/SurfGear/tree/dev/packages/virtual_keyboard

dependencies:
  flutter:
    sdk: flutter
  ink_widget:
    git:
      url: "https://gitlab.com/surfstudio/public/flutter-standard.git"
      path: packages/ink_widget
  surf_lint_rules:
    git:
      url: "https://gitlab.com/surfstudio/public/flutter-standard.git"
      path: packages/surf_lint_rules

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version: 1
  is_plugin: false
  path: virtual_keyboard
  hostUrl:
  separate_repo_url:
