name: surf_controllers
version: 1.0.1
description: Common controller for call dialogs
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/surf_controllers"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
