// Mocks generated by Mockito 5.0.13 from annotations
// in mwwm_example/test/features/auth/domain/usecase/authenticate_user_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mwwm_example/features/auth/domain/entities/auth_data.dart'
    as _i2;
import 'package:mwwm_example/features/auth/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAuthData extends _i1.Fake implements _i2.AuthData {}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get accessToken =>
      (super.noSuchMethod(Invocation.getter(#accessToken), returnValue: '')
          as String);
  @override
  _i4.Future<_i2.AuthData> authenticate({String? login, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #authenticate, [], {#login: login, #password: password}),
              returnValue: Future<_i2.AuthData>.value(_FakeAuthData()))
          as _i4.Future<_i2.AuthData>);
  @override
  String toString() => super.toString();
}
