name: flutter_test_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  cupertino_icons: ^0.1.2
  background_worker:
    git:
      url: https://gitlab.com/surfstudio/public/flutter-standard.git
      ref: project-LLC
      path: packages/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
