#!/usr/bin/env bash

build_type=release

### END FUNC

echo "Parameters" $1 $2
while [[ -n "$1" ]]; do # while loop starts

        case "$1" in

            -qa )           build_type=qa
                            ;;

            -release )      build_type=release
                            ;;
            -h )            dart ./script/android/build_impl/usage.dart
                            exit
                            ;;

            *)              dart ./script/android/build_impl/usage.dart
                            exit
                            ;;

            esac

         shift

done

### MAIN

dart ./script/android/build_impl/build.dart ${build_type}
