name: example
description: Example of application with bottom navigation bar
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bottom_navigation_bar:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  surf_lint_rules: ^1.0.0

flutter:
  uses-material-design: true
