name: example
description: A new Flutter module.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  render_metrics:
    path: ../

dev_dependencies:
  surf_lint_rules: ^1.0.0

flutter:
  uses-material-design: true
  module:
    androidX: false
    androidPackage: rendermetrics.example
    iosBundleIdentifier: rendermetrics.example
