# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_version "2.132.0"

default_platform(:android)

platform :android do

  desc "Submit a new debug build to Firebase App Distribution"
  lane :beta do
    puts "Firebase App Distribution | 32-bit"
    firebase_app_distribution(
        app: "1:867693323181:android:5d761bfb2896673e3eb724",                       #application identifier from Firebase Console
        apk_path: "../build/app/outputs/apk/dev/release/app-qa-armeabi-v7a.apk",    #relative path to the *.apk file
        groups: "surf",                                                             #desired testers group name
        release_notes: "QA x32",                                                    #release notes
        firebase_cli_path: "/usr/local/bin/firebase"                                #your local path to Firebase CLI
    )

    puts "Firebase App Distribution | 64-bit"
    firebase_app_distribution(
        app: "1:867693323181:android:5d761bfb2896673e3eb712",                   #application identifier from Firebase Console
        apk_path: "../build/app/outputs/apk/dev/release/app-qa-arm64-v8a.apk",  #relative path to the *.apk file
        groups: "TESTER_GROUP_NAME",                                            #desired testers group name
        release_notes: "QA x64",                                                #release notes
        firebase_cli_path: "/usr/local/bin/firebase"                            #your local path to Firebase CLI
    )

  end

  lane :release do
    #todo
    #crashlytics(
    #  api_token: 'YOUR_API_KEY',
    #  build_secret: 'YOUR_BUILD_SECRET',
    #  apk_path: "../build/app/outputs/apk/release/app-release-android-arm64.apk"
    #)

    #todo
    #crashlytics(
    #      api_token: 'YOUR_API_KEY',
    #      build_secret: 'YOUR_BUILD_SECRET',
    #      apk_path: "../build/app/outputs/apk/release/app-release.apk"
    #)
  end

end