# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_version "2.108.0"

default_platform(:android)

platform :android do

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    crashlytics(
      api_token: 'YOUR_API_KEY',
      build_secret: 'YOUR_BUILD_SECRET',
      apk_path: "../build/app/outputs/apk/release/app-qa-android-arm64.apk"
    )

    crashlytics(
          api_token: 'YOUR_API_KEY',
          build_secret: 'YOUR_BUILD_SECRET',
          apk_path: "../build/app/outputs/apk/release/app-qa.apk"
    )
  end

  lane :release do
    crashlytics(
      api_token: 'YOUR_API_KEY',
      build_secret: 'YOUR_BUILD_SECRET',
      apk_path: "../build/app/outputs/apk/release/app-release-android-arm64.apk"
    )

    crashlytics(
          api_token: 'YOUR_API_KEY',
          build_secret: 'YOUR_BUILD_SECRET',
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
    )
  end

#  desc "Deploy a new version to the Google Play"
#  lane :deploy do
#    gradle(task: "clean assembleRelease")
#    upload_to_play_store
#  end
end
