name: build otp_autofill

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/otp_autofill/**"
      - ".github/workflows/otp_autofill.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: packages/otp_autofill

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install lcov
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Run dependency validator
        run: |
          flutter pub global activate dependency_validator
          flutter pub global run dependency_validator:dependency_validator

      - name: Run analyzer
        run: flutter analyze --fatal-warnings --fatal-infos .

      - name: Run formatter
        run: flutter format --set-exit-if-changed .

      - name: Run tests
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        if: success()
        run: |
          flutter test --coverage
          mv coverage/lcov.info coverage/lcov.base.info
          flutter pub run ../../tools/coverage/fake_test_generator.dart
          flutter test --coverage --merge-coverage test/fake_test.dart
          flutter pub run ../../tools/coverage/patch_lcov.dart
          bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info -F otp_autofill

  package-analysis:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/otp_autofill

    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/otp_autofill
