name: Publish to pub.dev

on:
  push:
    branches:
      - main

jobs:
  publish_dev:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - analytics
          - auto_reload
          - bottom_navigation_bar
          - bottom_sheet
          - datalist
          - ink_widget
          - mwwm
          - otp_autofill
          - push_notification
          - relation
          - render_metrics
          - surf_controllers
          - surf_lint_rules
          - surf_logger
          - surf_mwwm
          - surf_util
          - swipe_refresh
      max-parallel: 1

    container:
      image: google/dart:latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Prepare check our conventions ⚙️
        run: dart pub upgrade
        working-directory: tools/ci-cd

      - name: Deploy unstable version 🚀
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
        run: dart run ../../tools/ci-cd/bin/ci.dart publish-dev-version
        working-directory: packages/${{matrix.package}}
