name: build surf_logger

on:
  push:
    branches:
      - dev
    paths:
      - "packages/surf_logger/**"
      - ".github/workflows/surf_logger.yaml"

  pull_request:
    branches:
      - dev
    paths:
      - "packages/surf_logger/**"
      - ".github/workflows/surf_logger.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    defaults:
      run:
        shell: bash
        working-directory: packages/surf_logger

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: dart pub get

      - name: Run dependency validator
        run: |
          dart pub global activate dependency_validator
          dart pub global run dependency_validator:dependency_validator

      - name: Run analyzer
        run: |
          dart analyze --fatal-warnings --fatal-infos lib
          dart analyze --fatal-warnings --fatal-infos test

      - name: Run formatter
        run: dart format --set-exit-if-changed .

      - name: Run tests
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        if: success()
        run: |
          dart pub run ../../tools/coverage/fake_test_generator.dart dart
          dart test --coverage=coverage
          dart pub global activate coverage
          dart pub global run coverage:format_coverage --packages=.packages -i coverage -o coverage/lcov.info --lcov --report-on=lib
          dart pub run ../../tools/coverage/patch_lcov.dart
          bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info -F surf_logger

  package-analysis:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/surf_logger

    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/surf_logger
